// type formData = {}
export const RegisterFormData:any = [
  [
    "Personal Details",
    [
      {
        id: "firstName",
        name: "firstName",
        label: "First Name",
        type: "text",
        placeholder: "Enter your first name",
        required: true,
      },
      {
        id: "LastName",
        name: "lastName",
        label: "Last Name",
        type: "text",
        placeholder: "Enter your last name",
        required: true,
      },
      {
        id: "email",
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "Enter email",
        required: true,
      },

           {
        id: "userName",
        name: "userName",
        label: "User Name",
        type: "text",
        placeholder: "Enter your username",
        required: true,
      },
      // {
      //   id: "mobileNumber",
      //   name: "mobileNumber",
      //   label: "Mobile Number",
      //   className: "",
      //   type: "text",
      //   placeholder: "Enter your mobile number",
      //   required: false,
      // },
      {
        group: [
          {
            id: "gender",
            name: "gender",
            label: "Gender",
            className: "gender",
            type: "select",
            required: true,
            placeholder: "Select gender",
            options: [
              { value: "Female", label: "Female" },
              { value: "Male", label: "Male" },
              { value: "Others", label: "Others" },
            ],
          },
          {
            id: "dateOfBirth",
            name: "dateOfBirth",
            className: "date",
            label: "Date of Birth",
            type: "text",
            required: true,
            onfocus: (e: any) => {
              return (e.target.type = "date");
            },
            placeholder: "Select date",
          },
        ],
      },
            {
        id: "password",
        name: "password",
        label: "Password",
        warning:"•8-characters-minimum •1-uppercase-character •1-number •No-spaces",
        className: "",
        type: "password",
        placeholder: "Enter password",
        required: true,
      },
      {
        id: "confirmPassword",
        name: "confirmPassword",
        label: "Confirm Password",
        className: "",
        type: "password",
        placeholder: "Confirm password",
        required: true,
      },
    ],
  ],
  // [
  //   "School Details",
  //   [
  //     {
  //       id: "SchoolName",
  //       name: "schoolname",
  //       label: "School Name",
  //       type: "text",
  //       placeholder: "Enter your school name",
  //       required: false,
  //     },

  //     {
  //       id: "schoolId",
  //       name: "schoolId",
  //       label: "School ID",
  //       type: "text",
  //       placeholder: "Enter school ID",
  //       required: false,
  //     },
  //     {
  //       id: "schoolCountry",
  //       name: "schoolCountry",
  //       label: "Country",
  //       type: "select",
  //       required: false,
  //       placeholder: "select your school country",
  //       options: [
  //         { value: "Being Fabulous", label: "Being Fabulous" },
  //         { value: "Ken Wheeler", label: "Ken Wheeler" },
  //         { value: "blues", label: "Blues" },
  //         { value: "rock", label: "Rock" },
  //         { value: "jazz", label: "Jazz" },
  //         { value: "Food", label: "Food" },
  //         { value: "ReasonML", label: "ReasonML" },
  //         { value: "Unicorns", label: "Unicorns" },
  //         { value: "Kittens", label: "Kittens" },
  //         { value: "orchestra", label: "Orchestra" },
  //       ],
  //     },
  //     {
  //       id: "faculty",
  //       name: "faculty",
  //       label: "Faculty",
  //       className: "",
  //       type: "select",
  //       placeholder: "select faculty",
  //       options: [
  //         { value: "Being Fabulous", label: "Being Fabulous" },
  //         { value: "Ken Wheeler", label: "Ken Wheeler" },
  //         { value: "blues", label: "Blues" },
  //         { value: "rock", label: "Rock" },
  //         { value: "jazz", label: "Jazz" },
  //         { value: "Food", label: "Food" },
  //         { value: "ReasonML", label: "ReasonML" },
  //         { value: "Unicorns", label: "Unicorns" },
  //         { value: "Kittens", label: "Kittens" },
  //         { value: "orchestra", label: "Orchestra" },
  //       ],
  //     },
  //     {
  //       id: "Department",
  //       name: "department",
  //       label: "Department",
  //       className: "",
  //       type: "select",
  //       placeholder: "select department",
  //       options: [
  //         { value: "Being Fabulous", label: "Being Fabulous" },
  //         { value: "Ken Wheeler", label: "Ken Wheeler" },
  //         { value: "blues", label: "Blues" },
  //         { value: "rock", label: "Rock" },
  //         { value: "jazz", label: "Jazz" },
  //         { value: "Food", label: "Food" },
  //         { value: "ReasonML", label: "ReasonML" },
  //         { value: "Unicorns", label: "Unicorns" },
  //         { value: "Kittens", label: "Kittens" },
  //         { value: "orchestra", label: "Orchestra" },
  //       ],
  //     },
  //     {
  //       label: "Account Type",
  //       group: [
  //         {
  //           type: "checkbox",
  //           label: "Student",
  //           id: "student",
  //           name: "student",
  //           className: "acc_type",
  //         },
  //         {
  //           type: "checkbox",
  //           label: "Staff",
  //           id: "staff",
  //           name: "staff",
  //           checked: false,
  //           disabled: true,
  //           className: "acc_type",
  //         },
  //       ],
  //     },
  //   ],
  // ],
  // [
  //   "Occupation Details",
  //   [
  //     {
  //       id: "occupation",
  //       name: "occupation",
  //       label: "Occupation",
  //       type: "text",
  //       placeholder: "Enter your occupation",
  //     },
  //     {
  //       id: "businessName",
  //       name: "businessName",
  //       label: "Business Name",
  //       type: "text",
  //       placeholder: "Enter your business name",
  //     },

  //     {
  //       id: "businessUrl",
  //       name: "businessUrl",
  //       label: "Business / Portfolio URL",
  //       className: "",
  //       type: "text",
  //       placeholder: "Enter URL",
  //     },
  //     {
  //       id: "occupationStatus",
  //       name: "occupationStatus",
  //       label: "Occupation Status",
  //       type: "select",
  //       placeholder: "select occupation Status",
  //       options: [
  //         { value: "jobless", label: "Jobless" },
  //         { value: "employed", label: "Employed" },
  //         { value: "hateWork", label: "Hate My Work" },
  //       ],
  //     },
  //   ],
  // ],
  // [
  //   "Profile Details",
  //   [
  //     {
  //       id: "profilePhoto",
  //       name: "profilePhoto",
  //       label: "UserName",
  //       type: "file",
  //       placeholder: "Enter your username",
  //       required: true,
  //     },
  //     {
  //       id: "userName",
  //       name: "userName",
  //       label: "UserName",
  //       type: "text",
  //       placeholder: "Enter your username",
  //       required: true,
  //     },
  //     {
  //       id: "country",
  //       name: "country",
  //       label: "Country",
  //       type: "select",
  //       placeholder: "select your country",
  //       required: true,
  //       options: [
  //         { value: "Being Fabulous", label: "Being Fabulous" },
  //         { value: "Ken Wheeler", label: "Ken Wheeler" },
  //         { value: "blues", label: "Blues" },
  //         { value: "rock", label: "Rock" },
  //         { value: "jazz", label: "Jazz" },
  //         { value: "Food", label: "Food" },
  //         { value: "ReasonML", label: "ReasonML" },
  //         { value: "Unicorns", label: "Unicorns" },
  //         { value: "Kittens", label: "Kittens" },
  //         { value: "orchestra", label: "Orchestra" },
  //       ],
  //     },
  //     {
  //       id: "websiteUrl",
  //       name: "websiteUrl",
  //       label: "Website URL",
  //       type: "text",
  //       placeholder: "Enter website Url",
  //     },
  //     {
  //       id: "password",
  //       name: "password",
  //       label: "Password",
  //       warning:"•8-characters-minimum •1-uppercase-character •1-number •No-spaces",
  //       className: "",
  //       type: "password",
  //       placeholder: "Enter password",
  //       required: true,
  //     },
  //     {
  //       id: "confirmPassword",
  //       name: "confirmPassword",
  //       label: "Confirm Password",
  //       className: "",
  //       type: "password",
  //       placeholder: "Confirm password",
  //       required: true,
  //     },
  //     {
  //       group: [
  //         {
  //           type: "checkbox",
  //           label: "I agree to StuLink's Terms of Service and Privacy Policy",
  //           id: "consent",
  //           name: "consent",
  //           className: "consent",
  //         },
  //       ],
  //     },
  //   ],
 // ],
  // [],
];
